// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

#ifndef PROTOBUF_Test_2eproto__INCLUDED
#define PROTOBUF_Test_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Test {
namespace protobuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Test_2eproto();
void protobuf_AssignDesc_Test_2eproto();
void protobuf_ShutdownFile_Test_2eproto();

class HeartInfo;

// ===================================================================

class HeartInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Test.protobuf.HeartInfo) */ {
 public:
  HeartInfo();
  virtual ~HeartInfo();

  HeartInfo(const HeartInfo& from);

  inline HeartInfo& operator=(const HeartInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HeartInfo& default_instance();

  void Swap(HeartInfo* other);

  // implements Message ----------------------------------------------

  inline HeartInfo* New() const { return New(NULL); }

  HeartInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HeartInfo& from);
  void MergeFrom(const HeartInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HeartInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 curtime = 1;
  bool has_curtime() const;
  void clear_curtime();
  static const int kCurtimeFieldNumber = 1;
  ::google::protobuf::int32 curtime() const;
  void set_curtime(::google::protobuf::int32 value);

  // required string hostip = 2;
  bool has_hostip() const;
  void clear_hostip();
  static const int kHostipFieldNumber = 2;
  const ::std::string& hostip() const;
  void set_hostip(const ::std::string& value);
  void set_hostip(const char* value);
  void set_hostip(const char* value, size_t size);
  ::std::string* mutable_hostip();
  ::std::string* release_hostip();
  void set_allocated_hostip(::std::string* hostip);

  // @@protoc_insertion_point(class_scope:Test.protobuf.HeartInfo)
 private:
  inline void set_has_curtime();
  inline void clear_has_curtime();
  inline void set_has_hostip();
  inline void clear_has_hostip();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr hostip_;
  ::google::protobuf::int32 curtime_;
  friend void  protobuf_AddDesc_Test_2eproto();
  friend void protobuf_AssignDesc_Test_2eproto();
  friend void protobuf_ShutdownFile_Test_2eproto();

  void InitAsDefaultInstance();
  static HeartInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HeartInfo

// required int32 curtime = 1;
inline bool HeartInfo::has_curtime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HeartInfo::set_has_curtime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HeartInfo::clear_has_curtime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HeartInfo::clear_curtime() {
  curtime_ = 0;
  clear_has_curtime();
}
inline ::google::protobuf::int32 HeartInfo::curtime() const {
  // @@protoc_insertion_point(field_get:Test.protobuf.HeartInfo.curtime)
  return curtime_;
}
inline void HeartInfo::set_curtime(::google::protobuf::int32 value) {
  set_has_curtime();
  curtime_ = value;
  // @@protoc_insertion_point(field_set:Test.protobuf.HeartInfo.curtime)
}

// required string hostip = 2;
inline bool HeartInfo::has_hostip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HeartInfo::set_has_hostip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HeartInfo::clear_has_hostip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HeartInfo::clear_hostip() {
  hostip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_hostip();
}
inline const ::std::string& HeartInfo::hostip() const {
  // @@protoc_insertion_point(field_get:Test.protobuf.HeartInfo.hostip)
  return hostip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartInfo::set_hostip(const ::std::string& value) {
  set_has_hostip();
  hostip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Test.protobuf.HeartInfo.hostip)
}
inline void HeartInfo::set_hostip(const char* value) {
  set_has_hostip();
  hostip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Test.protobuf.HeartInfo.hostip)
}
inline void HeartInfo::set_hostip(const char* value, size_t size) {
  set_has_hostip();
  hostip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Test.protobuf.HeartInfo.hostip)
}
inline ::std::string* HeartInfo::mutable_hostip() {
  set_has_hostip();
  // @@protoc_insertion_point(field_mutable:Test.protobuf.HeartInfo.hostip)
  return hostip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HeartInfo::release_hostip() {
  // @@protoc_insertion_point(field_release:Test.protobuf.HeartInfo.hostip)
  clear_has_hostip();
  return hostip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HeartInfo::set_allocated_hostip(::std::string* hostip) {
  if (hostip != NULL) {
    set_has_hostip();
  } else {
    clear_has_hostip();
  }
  hostip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostip);
  // @@protoc_insertion_point(field_set_allocated:Test.protobuf.HeartInfo.hostip)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace Test

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Test_2eproto__INCLUDED
