// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Test {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* HeartInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HeartInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Test_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Test_2eproto() {
  protobuf_AddDesc_Test_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Test.proto");
  GOOGLE_CHECK(file != NULL);
  HeartInfo_descriptor_ = file->message_type(0);
  static const int HeartInfo_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartInfo, curtime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartInfo, hostip_),
  };
  HeartInfo_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HeartInfo_descriptor_,
      HeartInfo::default_instance_,
      HeartInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartInfo, _has_bits_[0]),
      -1,
      -1,
      sizeof(HeartInfo),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartInfo, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Test_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HeartInfo_descriptor_, &HeartInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Test_2eproto() {
  delete HeartInfo::default_instance_;
  delete HeartInfo_reflection_;
}

void protobuf_AddDesc_Test_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_Test_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nTest.proto\022\rTest.protobuf\",\n\tHeartInfo"
    "\022\017\n\007curtime\030\001 \002(\005\022\016\n\006hostip\030\002 \002(\tB\002H\001", 77);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Test.proto", &protobuf_RegisterTypes);
  HeartInfo::default_instance_ = new HeartInfo();
  HeartInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Test_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Test_2eproto {
  StaticDescriptorInitializer_Test_2eproto() {
    protobuf_AddDesc_Test_2eproto();
  }
} static_descriptor_initializer_Test_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HeartInfo::kCurtimeFieldNumber;
const int HeartInfo::kHostipFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HeartInfo::HeartInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Test.protobuf.HeartInfo)
}

void HeartInfo::InitAsDefaultInstance() {
}

HeartInfo::HeartInfo(const HeartInfo& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Test.protobuf.HeartInfo)
}

void HeartInfo::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  curtime_ = 0;
  hostip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HeartInfo::~HeartInfo() {
  // @@protoc_insertion_point(destructor:Test.protobuf.HeartInfo)
  SharedDtor();
}

void HeartInfo::SharedDtor() {
  hostip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void HeartInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HeartInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HeartInfo_descriptor_;
}

const HeartInfo& HeartInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Test_2eproto();
  return *default_instance_;
}

HeartInfo* HeartInfo::default_instance_ = NULL;

HeartInfo* HeartInfo::New(::google::protobuf::Arena* arena) const {
  HeartInfo* n = new HeartInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HeartInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Test.protobuf.HeartInfo)
  if (_has_bits_[0 / 32] & 3u) {
    curtime_ = 0;
    if (has_hostip()) {
      hostip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool HeartInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Test.protobuf.HeartInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 curtime = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &curtime_)));
          set_has_curtime();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_hostip;
        break;
      }

      // required string hostip = 2;
      case 2: {
        if (tag == 18) {
         parse_hostip:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hostip()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->hostip().data(), this->hostip().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "Test.protobuf.HeartInfo.hostip");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Test.protobuf.HeartInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Test.protobuf.HeartInfo)
  return false;
#undef DO_
}

void HeartInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Test.protobuf.HeartInfo)
  // required int32 curtime = 1;
  if (has_curtime()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->curtime(), output);
  }

  // required string hostip = 2;
  if (has_hostip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hostip().data(), this->hostip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Test.protobuf.HeartInfo.hostip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->hostip(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Test.protobuf.HeartInfo)
}

::google::protobuf::uint8* HeartInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Test.protobuf.HeartInfo)
  // required int32 curtime = 1;
  if (has_curtime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->curtime(), target);
  }

  // required string hostip = 2;
  if (has_hostip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->hostip().data(), this->hostip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "Test.protobuf.HeartInfo.hostip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->hostip(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Test.protobuf.HeartInfo)
  return target;
}

int HeartInfo::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:Test.protobuf.HeartInfo)
  int total_size = 0;

  if (has_curtime()) {
    // required int32 curtime = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->curtime());
  }

  if (has_hostip()) {
    // required string hostip = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hostip());
  }

  return total_size;
}
int HeartInfo::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Test.protobuf.HeartInfo)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 curtime = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->curtime());

    // required string hostip = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hostip());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HeartInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Test.protobuf.HeartInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const HeartInfo* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HeartInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Test.protobuf.HeartInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Test.protobuf.HeartInfo)
    MergeFrom(*source);
  }
}

void HeartInfo::MergeFrom(const HeartInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Test.protobuf.HeartInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_curtime()) {
      set_curtime(from.curtime());
    }
    if (from.has_hostip()) {
      set_has_hostip();
      hostip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostip_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void HeartInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Test.protobuf.HeartInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HeartInfo::CopyFrom(const HeartInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Test.protobuf.HeartInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartInfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void HeartInfo::Swap(HeartInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HeartInfo::InternalSwap(HeartInfo* other) {
  std::swap(curtime_, other->curtime_);
  hostip_.Swap(&other->hostip_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HeartInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HeartInfo_descriptor_;
  metadata.reflection = HeartInfo_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// HeartInfo

// required int32 curtime = 1;
bool HeartInfo::has_curtime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void HeartInfo::set_has_curtime() {
  _has_bits_[0] |= 0x00000001u;
}
void HeartInfo::clear_has_curtime() {
  _has_bits_[0] &= ~0x00000001u;
}
void HeartInfo::clear_curtime() {
  curtime_ = 0;
  clear_has_curtime();
}
 ::google::protobuf::int32 HeartInfo::curtime() const {
  // @@protoc_insertion_point(field_get:Test.protobuf.HeartInfo.curtime)
  return curtime_;
}
 void HeartInfo::set_curtime(::google::protobuf::int32 value) {
  set_has_curtime();
  curtime_ = value;
  // @@protoc_insertion_point(field_set:Test.protobuf.HeartInfo.curtime)
}

// required string hostip = 2;
bool HeartInfo::has_hostip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void HeartInfo::set_has_hostip() {
  _has_bits_[0] |= 0x00000002u;
}
void HeartInfo::clear_has_hostip() {
  _has_bits_[0] &= ~0x00000002u;
}
void HeartInfo::clear_hostip() {
  hostip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_hostip();
}
 const ::std::string& HeartInfo::hostip() const {
  // @@protoc_insertion_point(field_get:Test.protobuf.HeartInfo.hostip)
  return hostip_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HeartInfo::set_hostip(const ::std::string& value) {
  set_has_hostip();
  hostip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Test.protobuf.HeartInfo.hostip)
}
 void HeartInfo::set_hostip(const char* value) {
  set_has_hostip();
  hostip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Test.protobuf.HeartInfo.hostip)
}
 void HeartInfo::set_hostip(const char* value, size_t size) {
  set_has_hostip();
  hostip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Test.protobuf.HeartInfo.hostip)
}
 ::std::string* HeartInfo::mutable_hostip() {
  set_has_hostip();
  // @@protoc_insertion_point(field_mutable:Test.protobuf.HeartInfo.hostip)
  return hostip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HeartInfo::release_hostip() {
  // @@protoc_insertion_point(field_release:Test.protobuf.HeartInfo.hostip)
  clear_has_hostip();
  return hostip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HeartInfo::set_allocated_hostip(::std::string* hostip) {
  if (hostip != NULL) {
    set_has_hostip();
  } else {
    clear_has_hostip();
  }
  hostip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hostip);
  // @@protoc_insertion_point(field_set_allocated:Test.protobuf.HeartInfo.hostip)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace Test

// @@protoc_insertion_point(global_scope)
